general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:
      priority_level_1: []
    parallels:
       priority_level_1: []
    ss_drivetrain:
      default: [st_drivetrain_percent]


  subsystems: [ss_drivetrain]

  input_booleans: [ipb_driver_right_trigger]

  input_numerics: [ipn_driver_right_x, ipn_driver_left_y]

  input_vectors: []

  output_numerics: [opn_drivetrain_left, opn_drivetrain_left]

  output_booleans: [opb_drivetrain_gear_shifter]


global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain:
  x: ipn_driver_right_x
  y: ipn_driver_left_y
  gear_shift: ipb_driver_left_trigger


log:
#  ips_selected_auto: true

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values:

